name: 🐛 Bug Report
description: Report a bug to help us improve Sync Board
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛
        
        Please fill out this form as completely as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the Contributing Guidelines
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: 📱 Device Type
      description: What device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 13.0, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: 🔧 Node.js Version (if running locally)
      description: What version of Node.js are you using?
      placeholder: "e.g., 18.17.0"

  - type: textarea
    id: console-errors
    attributes:
      label: 🔍 Console Errors
      description: Any errors in the browser console?
      placeholder: Paste console errors here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, videos, or additional information...

  - type: markdown
    attributes:
      value: |
        📸 **Screenshots/Videos**: If applicable, drag and drop images or videos here to help explain the problem.
